modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
logoFile = "icon.png"
displayURL = "https://space.bilibili.com/38982471"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[mixins]]
config = "${mod_id}.mixins.json"

[[dependencies."${mod_id}"]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "mekanism"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "avartia"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "eccentric_tome"
type = "optional"
versionRange = "*"
ordering = "BEFORE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "kaleidoscope_compat"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "create_ore_excavation_plus"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "ancientreforging"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "evolvedmekanism"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "mekanismadvancedgenerators"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "super_resolution"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "threatengl"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "modernui"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "veil"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "supplementaries"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "allthecompressed"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "allthecompatibility"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "mekmm"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "mekanism_extras"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"
