modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
logoFile = "icon.png"
displayURL = "https://space.bilibili.com/38982471"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[mixins]]
config = "${mod_id}.mixins.json"

[[dependencies."${mod_id}"]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "mekanism"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "avartia"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "eccentric_tome"
type = "optional"
versionRange = "*"
ordering = "BEFORE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "kaleidoscope_compat"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "create_ore_excavation_plus"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "ancientreforging"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "evolvedmekanism"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "mekanismadvancedgenerators"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "super_resolution"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "threatengl"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "modernui"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "veil"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "supplementaries"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "allthecompressed"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "allthecompatibility"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "mekmm"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "mekanism_extras"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "createnuclear"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "dndesires"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "traveloptics"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "igleelib"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "jaopca"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "create_sa"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "createsa_tank_fix"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "irons_spellbooks"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "irons_apothic"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "silentgear"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "apotheosisdeschelper"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "apotheosis"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "hazennstuff"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "hazentouvelib"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "steampowered"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "compactflap"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "aeronautics_dyeable_components"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "aeroworks"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "moonlight"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "extra_apoth_compat"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "aces_spell_utils"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "tunes_n_tomes"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "alshanex_familiars"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "familiarslib"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "toomanyrecipeviewers"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "ftbquests"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "questshop"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "ccterminals"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

