modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
logoFile = "icon.png"
displayURL = "https://space.bilibili.com/38982471"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[mixins]]
config = "${mod_id}.mixins.json"

[[dependencies."${mod_id}"]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "mekanism"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "avartia"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "eccentric_tome"
type = "optional"
versionRange = "*"
ordering = "BEFORE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "kaleidoscope_compat"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "create_ore_excavation_plus"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "ancientreforging"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "evolvedmekanism"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "mekanismadvancedgenerators"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "super_resolution"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "threatengl"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "modernui"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "veil"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "supplementaries"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "allthecompressed"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "allthecompatibility"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "mekmm"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "mekanism_extras"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "createnuclear"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "dndesires"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "traveloptics"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "igleelib"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "jaopca"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "create_sa"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "createsa_tank_fix"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "irons_spellbooks"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "irons_apothic"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "silentgear"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "apotheosisdeschelper"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "apotheosis"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "hazennstuff"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "hazentouvelib"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "steampowered"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "compactflap"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "aeronautics_dyeable_components"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "aeroworks"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "moonlight"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "extra_apoth_compat"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "aces_spell_utils"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "tunes_n_tomes"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "alshanex_familiars"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "familiarslib"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "toomanyrecipeviewers"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "ftbquests"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "questshop"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "ccterminals"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "fluxnetworks"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "densemekanism"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "attributefix"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "prickle"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "alltheores"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "compactmachines"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "croptopia"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "hostilenetworks"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "spectrum"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "neoecoae"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "create_submarine"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "apotheosis_things"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "create"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "apothsiscreate"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "aerocali"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "ali"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "create_aeronautics_automated_logistics"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "create_apothic_enchanting"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "mekanism_weaponry"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "mek_x_star"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "vista_plus"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "ae2peat"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "modernfix"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "fluidlogistics"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "exspectriments"
type = "optional"
versionRange = "*"
ordering = "BEFORE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "tipsmod"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "ae2helpers"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "packagedauto"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "packagedavaritia"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "packagedexcrafting"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "packagedmekemicals"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "powerful_dummy"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "ae2wtlib"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "ae2"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "createmetalogistics"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "hazennstuff"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "createmechanicalcompanion"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "createmechanicalcompanion"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "protection_pixel"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "create_fantasizing"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "customrecipe"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "createcardboardthings"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "create_optical"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "irons_jewelry"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "maid_storage_manager"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "touhou_little_maid"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "touhou_little_maid_spell"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "touhou_lost_maid"
type = "optional"
versionRange = "*"
ordering = "BEFORE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "flavor_immersed_daily"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "kaleidoscope_cookery"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "ccbr"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "kaleidoscope_tavern"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "integrated_villages"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "bountiful"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "fidworkblock"
type = "optional"
versionRange = "*"
ordering = "AFTER"

[[dependencies."${mod_id}"]]
modId = "waystones"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "extendedcrafting"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "packagedexcrafting"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "applied_extended_crafting"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "extremesoundmuffler"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "createvoidway"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "northstar"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "apothic_enchanting"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "neoguanniao"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "sophisticatedcore"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "sophisticatedstorage"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "trashslot"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "apothic_attributes"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "additional_attributes"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "additionalentityattributes"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "irons_lib"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "bits_n_bobs"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "terrablender"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "thaumic_tinkerer"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "thaumcraft"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "forbiddenmagic"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "thaumcraftcelestial"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "xaeroworldmap"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"
